FROM node:22-alpine

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /usr/app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . ./

RUN pnpm run build

EXPOSE 8081

CMD [ "node", "dist/server.js" ]
# CMD ["pnpm", "run", "dev"] # For development